// Generated by CoffeeScript 1.4.0
(function() {
  var Model, _;

  _ = require("underscore");

  module.exports = Model = (function() {
    /*
    */

    function Model(data, options) {
      this.data = data;
      if (options == null) {
        options = {};
      }
      _.extend(this, options);
    }

    /*
    */


    Model.prototype.validate = function(callback) {
      return this.schema.test(this.data, callback);
    };

    return Model;

  })();

}).call(this);
