// Generated by CoffeeScript 1.4.0
(function() {
  var Bindable, Model, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require("underscore");

  Bindable = require("bindable");

  module.exports = Model = (function(_super) {

    __extends(Model, _super);

    /*
    */


    function Model(data, options) {
      this.data = data != null ? data : {};
      if (options == null) {
        options = {};
      }
      Model.__super__.constructor.call(this, this.data);
      _.extend(this, options);
    }

    /*
    */


    Model.prototype.validate = function(callback) {
      if (!this.schema) {
        return callback();
      }
      return this.schema.test(this.data, callback);
    };

    return Model;

  })(Bindable);

}).call(this);
